name: "Build docker image for web"

on:
  schedule:
    # Run everyday sunday.
    #
    # First field is minute, second is hour of the day. Last is day of week,
    # 0 being Sunday.
    #
    # Add a few minutes of offset to avoid scheduling on exact hourly
    # boundaries (recommended by GitHub to avoid congestion).
    #
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    # https://crontab.guru/
    #
    - cron: "13 4 * * 0"
  # Also allow manually running the workflow
  workflow_dispatch:
  # And on tags
  push:
    branches:
      - "main"
    tags:
      - "photos-*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to GitHub Packages Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            name=ghcr.io/${{ github.repository_owner }}/ente-web
            name=docker.io/${{ github.repository_owner }}/ente-web
          tags: |
            type=match,pattern=photos-v(\d.\d.\d),group=1
            type=edge,branch=main
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: web
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
